#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""ae

Usage:
    ae fetch [(-m | --mms-id) <mms>] [(-o | --out-file) <of>] [(-e | --error-file) <ef>] [(-a | --api-key) <api>]
    ae update [(-m | --mms-id) <mms>] [(-i | --input-file) <if>] [(-a | --api-key) <api>]
    ae gui
"""
from settings import api_key, mms_id, output_file, error_file, base_url, input_file
from docopt import docopt
from AE import fetch, update
from subprocess import call

if __name__ == '__main__':
    args = docopt(__doc__)
    
    if args['-m'] or args['--mms-id']:
        mms_id = args['<mms>']

    if args['-o'] or args['--output-file']:
        output_file = args['<of>']

    if args['-e'] or args['--error-file']:
        error_file = args['<ef>']   

    if args['-a'] or args['--api-key']:
        api_key = args['<api>']

    if args['-i'] or args['--input-file']:
        input_file = args['<if>'] 

    if args['fetch']:
        fetch(mms_id, output_file, error_file, api_key, base_url)
        
    if args['update']:
        update(mms_id, input_file, api_key, base_url)
        
    if args['gui']:
        call(['ae_gui'])
        