#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""ae_batch

Usage:
    ae_batch [(-i | --input-file) <if>] [(-o | --output-file) <of>] [(-e | --error-file) <ef>] [(-a | --api-key) <api>] <lf>      
"""

from settings import api_key, mms_id, input_file, output_file, error_file, base_url
from AE import fetch, update
from docopt import docopt

if __name__ == '__main__':
    args = docopt(__doc__)

    if args['-o'] or args['--output-file']:
        output_file = args['<of>']

    if args['-i'] or args['--input-file']:
        input_file = args['<if>']

    if args['-e'] or args['--error-file']:
        error_file = args['<ef>']   

    if args['-a'] or args['--api-key']:
        api_key = args['<api>']

    list_file = args['<lf>']

    mms_id_list = []
    with open(list_file, 'r') as fh:
        for line in fh:
            list_file.append(line.strip())

    for mms_id in mms_id_list:
        fetch(mms_id, output_file, error_file, api_key, base_url)
        update(mms_id, input_file, api_key, base_url)

    