#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from settings import api_key, input_file, output_file, error_file, base_url
from AE import fetch, update
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('-o', '--output-file')
parser.add_argument('-i', '--input-file')
parser.add_argument('-e', '--error-file')
parser.add_argument('-a', '--api-key')
parser.add_argument('mms_id_file')
args = parser.parse_args()

mms_id_list = []
with open(args.mms_id_file, 'r') as fh:
    for line in fh:
        mms_id_list.append(line.strip())

for mms_id in mms_id_list:
    fetch(mms_id, output_file, error_file, api_key, base_url)
    update(mms_id, input_file, api_key, base_url)