#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""ae_fetch

Usage:
    ae_fetch [(-m | --mms-id) <mms>] [(-o | --output-file) <of>] [(-e | --error-file) <ef>] [(-a | --api-key) <api>]
"""

from settings import api_key, mms_id, output_file, error_file, base_url
from AE import fetch
from docopt import docopt

if __name__ == '__main__':
    args = docopt(__doc__)
    
    if args['-m'] or args['--mms-id']:
        mms_id = args['<mms>']

    if args['-o'] or args['--output-file']:
        output_file = args['<of>']

    if args['-e'] or args['--error-file']:
        error_file = args['<ef>']   

    if args['-a'] or args['--api-key']:
        api_key = args['<api>']

    fetch(mms_id, output_file, error_file, api_key, base_url)
    

  